-- MySQL Script generated by MySQL Workbench
-- Mon 12 Oct 2015 23:29:03 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema fastpress_app
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fastpress_app` DEFAULT CHARACTER SET latin1 ;
USE `fastpress_app` ;

-- -----------------------------------------------------
-- Table `fastpress_app`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `username` VARCHAR(100) NOT NULL COMMENT '',
  `email` VARCHAR(255) NOT NULL COMMENT '',
  `password` VARCHAR(255) NOT NULL COMMENT '',
  `is_admin` TINYINT(4) NOT NULL DEFAULT '0' COMMENT '',
  `date_added` DATETIME NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '');


-- -----------------------------------------------------
-- Table `fastpress_app`.`pages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pages` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `slug` VARCHAR(255) NOT NULL COMMENT '',
  `title` VARCHAR(255) NOT NULL COMMENT '',
  `tags` VARCHAR(255) NOT NULL COMMENT '',
  `content` TEXT NOT NULL COMMENT '',
  `date_added` DATETIME NOT NULL COMMENT '',
  `is_active` BIT(1) NOT NULL COMMENT '',
  `users_id` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_pages_users_idx` (`users_id` ASC)  COMMENT '',
  CONSTRAINT `fk_pages_users`
    FOREIGN KEY (`users_id`)
    REFERENCES `users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `fastpress_app`.`tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tags` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `tag` VARCHAR(80) NOT NULL COMMENT '',
  `date_added` DATETIME NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '');


-- -----------------------------------------------------
-- Table `fastpress_app`.`pages_tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pages_tags` (
  `pages_id` INT(11) NOT NULL COMMENT '',
  `tags_id` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`pages_id`, `tags_id`)  COMMENT '',
  INDEX `fk_pages_tags_tags1_idx` (`tags_id` ASC)  COMMENT '',
  INDEX `fk_pages_tags_pages1_idx` (`pages_id` ASC)  COMMENT '',
  CONSTRAINT `fk_pages_tags_pages1`
    FOREIGN KEY (`pages_id`)
    REFERENCES `fastpress_app`.`pages` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pages_tags_tags1`
    FOREIGN KEY (`tags_id`)
    REFERENCES `fastpress_app`.`tags` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

