CREATE TABLE `tb_account` (	  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
	  `description` varchar(100) NOT NULL DEFAULT '',
	  `user_id` int(11) NOT NULL,
	  `currency_id` int(11) unsigned NOT NULL,
	  PRIMARY KEY (`id`),
	  KEY `user_id` (`user_id`),
	  KEY `currency_id` (`currency_id`),
	  CONSTRAINT `tb_account_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `tb_user` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
	  CONSTRAINT `tb_account_ibfk_2` FOREIGN KEY (`currency_id`) REFERENCES `tb_currency` (`id`)	) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `tb_cashbook` (	  `id` int(11) NOT NULL AUTO_INCREMENT,
	  `value` float NOT NULL,
	  `description` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL,
	  `date` date NOT NULL,
	  `is_pending` tinyint(1) NOT NULL DEFAULT '0',
	  `attachment` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
	  `inc_datetime` datetime DEFAULT NULL COMMENT 'insert date',
	  `edit_datetime` datetime DEFAULT NULL COMMENT 'edit date',
	  `user_id` int(11) NOT NULL,
	  `category_id` int(11) NOT NULL,
	  `type_id` int(11) NOT NULL,
	  PRIMARY KEY (`id`),
	  KEY `fk_tb_cashbook_tb_user1_idx` (`user_id`),
	  KEY `fk_tb_cashbook_tb_category1_idx` (`category_id`),
	  KEY `fk_tb_cashbook_tb_type1_idx` (`type_id`),
	  CONSTRAINT `fk_tb_cashbook_tb_category1` FOREIGN KEY (`category_id`) REFERENCES `tb_category` (`id_category`) ON DELETE NO ACTION ON UPDATE NO ACTION,
	  CONSTRAINT `fk_tb_cashbook_tb_type1` FOREIGN KEY (`type_id`) REFERENCES `tb_type` (`id_type`) ON DELETE NO ACTION ON UPDATE NO ACTION,
	  CONSTRAINT `fk_tb_cashbook_tb_user1` FOREIGN KEY (`user_id`) REFERENCES `tb_user` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION	) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='Control financial movement';

CREATE TABLE `tb_category` (	  `id_category` int(11) NOT NULL AUTO_INCREMENT,
	  `desc_category` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
	  `hexcolor_category` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL,
	  `user_id` int(11) NOT NULL,
	  PRIMARY KEY (`id_category`),
	  KEY `fk_tb_category_tb_user1_idx` (`user_id`),
	  CONSTRAINT `fk_tb_category_tb_user1` FOREIGN KEY (`user_id`) REFERENCES `tb_user` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION	) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='Categories of entries: Water,
 light,
 card,
 etc.';

CREATE TABLE `tb_currency` (	  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
	  `name` varchar(100) DEFAULT NULL,
	  `short_name` varchar(10) DEFAULT NULL,
	  `iso_code` varchar(3) NOT NULL DEFAULT '',
	  `currency_rate` decimal(10,
0) DEFAULT NULL,
	  `user_id` int(11) DEFAULT NULL,
	  PRIMARY KEY (`id`),
	  KEY `user_id` (`user_id`),
	  CONSTRAINT `tb_currency_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `tb_user` (`id`) ON DELETE CASCADE ON UPDATE CASCADE	) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `tb_migration` (	  `version` varchar(180) CHARACTER SET latin1 NOT NULL,
	  `apply_time` int(11) DEFAULT NULL,
	  PRIMARY KEY (`version`)	) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `tb_profile` (	  `id` int(11) NOT NULL AUTO_INCREMENT,
	  `user_id` int(11) NOT NULL,
	  `create_time` timestamp NULL DEFAULT NULL,
	  `update_time` timestamp NULL DEFAULT NULL,
	  `full_name` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
	  `language` varchar(100) COLLATE utf8_unicode_ci NOT NULL DEFAULT 'en',
	  PRIMARY KEY (`id`),
	  KEY `tb_profile_user_id` (`user_id`) USING BTREE,
	  CONSTRAINT `tb_profile_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `tb_user` (`id`)	) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `tb_role` (	  `id` int(11) NOT NULL AUTO_INCREMENT,
	  `name` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
	  `create_time` timestamp NULL DEFAULT NULL,
	  `update_time` timestamp NULL DEFAULT NULL,
	  `can_admin` smallint(6) NOT NULL DEFAULT '0',
	  PRIMARY KEY (`id`)	) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `tb_type` (	  `id_type` int(11) NOT NULL AUTO_INCREMENT,
	  `desc_type` varchar(45) CHARACTER SET latin1 NOT NULL,
	  `hexcolor_type` varchar(45) CHARACTER SET latin1 DEFAULT NULL,
	  `icon_type` varchar(45) CHARACTER SET latin1 DEFAULT NULL,
	  PRIMARY KEY (`id_type`)	) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='Movement Type: Debit,
 Credit';

CREATE TABLE `tb_user` (	  `id` int(11) NOT NULL AUTO_INCREMENT,
	  `role_id` int(11) NOT NULL,
	  `status` smallint(6) NOT NULL,
	  `email` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
	  `new_email` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
	  `username` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
	  `password` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
	  `auth_key` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
	  `api_key` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
	  `login_ip` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
	  `login_time` timestamp NULL DEFAULT NULL,
	  `create_ip` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
	  `create_time` timestamp NULL DEFAULT NULL,
	  `update_time` timestamp NULL DEFAULT NULL,
	  `ban_time` timestamp NULL DEFAULT NULL,
	  `ban_reason` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
	  PRIMARY KEY (`id`),
	  UNIQUE KEY `tb_user_email` (`email`) USING BTREE,
	  UNIQUE KEY `tb_user_username` (`username`) USING BTREE,
	  KEY `tb_user_role_id` (`role_id`) USING BTREE,
	  CONSTRAINT `tb_user_ibfk_1` FOREIGN KEY (`role_id`) REFERENCES `tb_role` (`id`)	) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `tb_user_auth` (	  `id` int(11) NOT NULL AUTO_INCREMENT,
	  `user_id` int(11) NOT NULL,
	  `provider` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
	  `provider_id` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
	  `provider_attributes` text COLLATE utf8_unicode_ci NOT NULL,
	  `create_time` timestamp NULL DEFAULT NULL,
	  `update_time` timestamp NULL DEFAULT NULL,
	  PRIMARY KEY (`id`),
	  KEY `tb_user_auth_provider_id` (`provider_id`) USING BTREE,
	  KEY `tb_user_auth_user_id` (`user_id`) USING BTREE,
	  CONSTRAINT `tb_user_auth_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `tb_user` (`id`)	) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `tb_user_key` (	  `id` int(11) NOT NULL AUTO_INCREMENT,
	  `user_id` int(11) NOT NULL,
	  `type` smallint(6) NOT NULL,
	  `key_value` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
	  `create_time` timestamp NULL DEFAULT NULL,
	  `consume_time` timestamp NULL DEFAULT NULL,
	  `expire_time` timestamp NULL DEFAULT NULL,
	  PRIMARY KEY (`id`),
	  UNIQUE KEY `tb_user_key_key` (`key_value`) USING BTREE,
	  KEY `tb_user_key_user_id` (`user_id`) USING BTREE,
	  CONSTRAINT `tb_user_key_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `tb_user` (`id`)	) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

